### PR TITLE
Translate docs to korean (Re PR)

### PR DESCRIPTION
**Pull request by preco21**
Not yet fully completed, but main tutorials and apis translation has been completed. (except one file)
I will be also translate the other files soon!

### CODE REVIEW

**Comment by steelbrain** [comment]
@hokein thoughts?

**Comment by zcbenz** [comment]
I don't understand Korean so I'm clicking merge button blindly, thanks!

**Comment by thomasjo** [comment]
> I don't understand Korean so I'm clicking merge button blindly, thanks!

:see_no_evil:

**Comment by preco21** [comment]
Thanks for merging!
I translate more docs in to korean soon!

**Comment by dalinaum** [comment]
His translation looks good. But these files are not completely translated. I think he should seperate fully translated files from his next work and push his next PR clearly.

**Pull request merged**
