### PR TITLE
Fixing FrameSubscriber memory issue

### PR DESCRIPTION
**Pull request by brenca**
I restructured `FrameSubscriber` a bit to only give Chromium a nested class instead of the whole, so when the nested class gets deleted by a `endFrameSubscription()` call, we can still handle the callbacks properly (`OnFrameDelivered` callbacks are sometimes called after the subscription has already ended), and if we don't expect any more callbacks (we count how many `ShouldCaptureFrame` and `OnFrameDelivered` calls we had), we can delete the actual `FrameSubscriber` (the last `OnFrameDelivered` calls the delete or if we're not waiting for callbacks by the time the nested class gets destroyed, the destructor of that calls the delete).

### CODE REVIEW

**Comment by brenca** [comment]
Fixes #4441

**Comment by Mr0grog** [comment]
This works for me, thanks! However, because it still calls the callback if there are pending frames, a JavaScript subscriber can still receive more frames after unsubscribing. Is that right/intended?

As a user reading the docs, I would probably expect to immediately stop receiving frames after calling `endFrameSubscription()`. If the current behavior is the one we want, it would be nice if I could receive a number of pending frames or some kind of helpful info either when I unsubscribe or as an argument to the subscriber callback.

**Comment by brenca** [comment]
We already discard the last frame, so I guess it's not a big deal if we lose another one/two frames.

**Comment by Mr0grog** [comment]
Thanks! Works great here.

**Comment by zcbenz** [comment]
Thanks!

**Pull request merged**
