### PR TITLE
Upgrade to Node v5.1.1

### PR DESCRIPTION
**Pull request by zcbenz**

### CODE REVIEW

**Comment by thomasjo** [comment]
Is this going to prevent us from upgrading Electron in Atom? I thought we wanted to stick to LTS releases? /cc @atom/feedback

**Comment by zcbenz** [comment]
V8 4.7 is compatible with V8 4.5's APIs, so we don't need to update a bunch of modules this time.

Using Node with an unmatched V8 version is usually a bad idea, since Node might rely on certain V8 version's behaviors.

**Comment by thomasjo** [comment]
OK, so this upgrade was necessary in order to bump Chromium to v47?

When we bump Electron in Atom we will have to resolve issues with npm v3 though; it's not playing nice right now (unless someone has resolved the issues in the last few weeks). Hopefully not too big of a hurdle. But my comment regarding Node LTS was specifically related to stability concerns.

**Comment by zcbenz** [comment]
> OK, so this upgrade was necessary in order to bump Chromium to v47?

Yeah.

The stability of Node LTS is largely depending on using an old but stable V8 version, so every time we bump the Chrome version, we break the stability a bit.

**Pull request merged**
