### PR TITLE
Fix url to WebContents.send example

### PR DESCRIPTION
**Pull request by petrfelzmann**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Where were you seeing this not working?

When I click it from https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#webviewsendchannel-args it does seem to anchor correctly on https://github.com/atom/electron/blob/master/docs/api/browser-window.md#webcontentssendchannel-args

**Comment by petrfelzmann** [comment]
You can observe the issue on live site. [Here](http://electron.atom.io/docs/v0.30.0/api/web-view-tag/#lt-webview-gt-send-channel-args) you can see the sentence *"See WebContents.send for examples."* containing the corrupted link to WebContents.send. The correct link should be
http://electron.atom.io/docs/v0.30.0/api/browser-window/#webcontents-send-channel-args

**Comment by jlord** [comment]
I think .com and the Jekyll Electron site are generating different ids for the same header? :confused:

**Comment by zcbenz** [comment]
> I think .com and the Jekyll Electron site are generating different ids for the same header? 

.com seems to remove all punctuation in ID except for `-`.

**Comment by jlord** [comment]
Lemme give this a think—we've run into lots of problems with the markdown parser but have limited options if we want to use the default ones for Jekyll on GitHub Pages. May end up just doing it ourselves and pushing the built site. 

Since this is more an issue with the live site I'm going to close here and open there :+1:

**Pull request closed without merging**
