### PR TITLE
Enhancement/add app restart

### PR DESCRIPTION
**Pull request by leethomas**
Closes https://github.com/atom/electron/issues/539

Not sure if this is the best way to do it but it seemed like the most straightforward.  It works on OS X/Linux but it's a work in progress because I'd like to get it working for Windows as well. ~~I need a way to check if a PID still exists on Windows- but I'm trying to avoid adding pywin32 as a dependency. Any suggestions?~~ should work on Windows now.

### CODE REVIEW

**Comment by etiktin** [comment]
Your current commits add a dependency on python, so every user that ends up using an app that calls `app.restart` will need python installed. I suggest implementing it in coffeescript or C++.

**Comment by zcbenz** [comment]
The `script/restart` script is not shipped with Electron, so no matter whether you use node or python it won't work anyway, except for when using it in the cloned Electron repo.

Also `node` is an even worse choice than python, no operating system is shipping node by default.

The decent way of implementing `app.restart` is to use shell script on POSIX systems, and batch script on Windows. The script should be generated dynamically when `app.restart` is called, so we don't have to add another file in the distribution.

**Comment by etiktin** [comment]
Instead of using node you can use electron as node (process.execPath with ELECTRON_RUN_AS_NODE env variable). In regards to the script, we can add it to atom.asar and extract it to temp before executing the command.
@zcbenz, what do you think?

**Comment by zcbenz** [comment]
> Instead of using node you can use electron as node (process.execPath with ELECTRON_RUN_AS_NODE env variable). In regards to the script, we can add it to atom.asar and extract it to temp before executing the command.

It sounds good to me, better than writing shell scripts :+1:. We don't need to extract the script though, the node mode of Electron can read the asar archive directly.

**Comment by leethomas** [comment]
@zcbenz @etiktin Will ELECTRON_RUN_AS_NODE work with apps that have already been packaged for their respective OS?

**Comment by etiktin** [comment]
@leethomas, I'm not sure I understand your question. Are you asking if you can run an existing app with that env var? You can run a node script that is located in your app folder or asar, but it will fail if you try to run anything that uses Electron's APIs.

**Comment by leethomas** [comment]
Nvm on the previous question. @zcbenz  I was reading the app-distribution docs and read that you can only use `child_process.execFile` when reading from asar archives. Since we need to execute a binary we'll have to extract it anyway, no?

**Comment by zcbenz** [comment]
@leethomas Node.js uses `fs.readFileSync` to read a script and execute it, the node mode of Electron behaves the same with Node.js.

**Comment by leethomas** [comment]
I'm not sure if I'm imagining the same workflow you are. Here's what's in my head: `app.restart()`(launches resource_path/atom.asar/restart.js, then kills itself)` -> `restart.js` (waits for the app to quit if it hasn't already, then execute the binary for the app). The last part is where I'm stuck. If `restart.js` uses `fs.readFileSync` calls another script...well then that's 2 scripts, right? I tried using `child_process.exec` from within `restart.js` but it didn't work of course.

**Comment by zcbenz** [comment]
Ideal workflow is:

1. child_process.fork('/path/to/restart.js', [ argsForRestarting ]);
2. app.quit();
2. In restart.js: wait for the process to quit and then restart the app.

Reading the source code is the fastest way to get questions answered.

**Comment by leethomas** [comment]
Thanks, realized I was overcomplicating things

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Program.cs#L510 shows how to open your parent's PID and wait for it to exit

**Comment by zcbenz** [comment]
I'm closing this because there hasn't been any update since last code review, will reopen when there is update.

**Pull request closed without merging**
