### PR TITLE
protocol: supporting async request jobs

### LINKED ISSUE #410: Async protocol job
Is there a way to return something that is not yet available from a custom protocol handler?

```js
protocol.registerProtocol('atom', function(request) {
  var url = request.url.substr(7)
  return new protocol.RequestAsyncStringJob(function(cb) {
    somewhere.fetch(url, function(data) { cb({ encoding, mimeType, data }); });
  });
});
```

My intent is to lazily fetch data from network if not yet available locally or local cached value is outdated.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #410 

Have started with an api like

```js
protocol.RequestAsyncJob(<jobtype>, function(cb) {
  cb(<object>)
})
```

- [x] support all existing sync jobs
- [x] Add Tests
- [ ] buffer data goes out of context in callback

### CODE REVIEW

**Comment by deepak1556** [comment]
Changed the async api to reflect synchronous version.

```
protocol.RequestAsyncFileJob(function (cb) {
  cb({path: path})
});
```

- [ ] Fix asynchronous buffer job
- [ ] Confirm api
- [ ] add parameter guards to async api

**Comment by zcbenz** [comment]
An `RequestAsyncBufferJob` should be enough to cover all cases, the purpose of async job is to support streaming data, for which `Buffer` is the only type used.

The `cb` can be called as `cb(errorCode, data)` like traditional Node.js apps.

**Comment by deepak1556** [comment]
> The cb can be called as cb(errorCode, data) like traditional Node.js apps.

:+1: 

@zcbenz So what would be the type of `data` be,  a node buffer?

**Comment by zcbenz** [comment]
> @zcbenz So what would be the type of data be, a node buffer?

Yeah.

**Comment by steelbrain** [comment]
@zcbenz Can that buffer be a stream-in-progress buffer? I mean, can I use the request library and pass it's response buffer and it'll still load **all** of it's contents?

**Comment by deepak1556** [comment]
about `cb(errorCode, data)` , the data is obsolete when errorCode is provided as we can start only one job ?

**Comment by zcbenz** [comment]
The async job should provide an streaming interface instead of just an asynchronous version of buffer job. A real-life example is like this:

```coffeescript
var request = require 'request'

protocol.registerProtocol 'atom-async-buffer-job', (url) ->
  stream = request.get(getRedirectUrl(url))
  return new protocol.RequestAsyncJob (callback) ->
    stream.on 'error', (error) ->
      callback(getErrorCode(error))
    stream.on 'data', (data) ->
      callback(0, data)
    stream.on 'finish', ->
      callback(EOF)
```

The `callback` will be called when:
* An error happens and the request would be aborted.
* New data arrives.
* All data has been read and the request is finished.

And the `errorCode` needs to represent:
* An error.
* Everything is OK and continue read.
* EOF.

**Comment by steelbrain** [comment]
I wonder how `did-get-response-details` and events like that would work with it.

**Comment by frozeman** [comment]
Any progress on that?

**Comment by steelbrain** [comment]
@zcbenz what do you think of this API?
```js
var request = require 'request'

protocol.registerProtocol 'atom-async-buffer-job', (url) ->
  stream = request.get(getRedirectUrl(url))
  return new protocol.RequestAsyncJob (outputStream) ->
    stream.pipe(outputStream)
```
The errors or eof and stuff like that will automatically be forwarded to the output stream.

**Comment by frozeman** [comment]
I don't know much about streaming output, but is it possible to basically hide a local server behind a custom protocol?

e.g. `bzz://123455` -> `http://localhost:8050/123455`

So that the content, which `http://localhost:8050/123455` would deliver comes through the custom protocol.

Is this possible when only providing async stream and not asyncString ?

**Comment by steelbrain** [comment]
It's possible in both cases, it's just that asyncString would be a blocking operation, nothing would be shown until everything has finished.

**Comment by zcbenz** [comment]
@steelbrain It is a very nice API, but it would be extremely hard to implement in C++.

**Comment by frozeman** [comment]
Why is that closed? Won't async be implemented?

**Comment by steelbrain** [comment]
:broken_heart:

**Comment by deepak1556** [comment]
I havent yet come back to this PR, will take sometime, didnt wanna block any1else wanted to take a stab at it in the mean time.

**Comment by frozeman** [comment]
@deepak1556 Could you resume this PR, so now that we have standard compatible protocols that we can actual stream data e.g. from a local server over the custom protocol?

**Comment by frozeman** [comment]
@deepak1556 Do you have time now to resume this one?

**Comment by steelbrain** [comment]
Bump.

**Comment by deepak1556** [comment]
@frozeman @steelbrain will look into this today.

**Comment by frozeman** [comment]
That would be awesome!
I really need that feature, otherwise the whole custom protocol thing doesn't real make sense.

**Comment by frozeman** [comment]
Concerning the API. i'm more in favor of @zcbenz API proposal, as it allows for different uses cases beyond redirect requests. So a callback is a good solution here, just the steps (error, send data, and tell when the req is finished) need to be clearified.

@steelbrain youre API is simple, but would restrain the stuff you return async to a stream output.

**Comment by steelbrain** [comment]
@frozeman the stream one is actually quite simple, there are different stream events like `responseDetails` and stuff, so electron's coffee part could just emulate that and notify the c++ side about it, that would be like
```coffee
class protocol.RequestAsyncJob
  constructor: (@outputStream) ->
    outputStream.on('responseDetails', @gotResponseDetails)
    outputStream.on('data', @gotData)
    outputStream.on('end', @gotEnd)

  gotResponseDetails: (responseDetails) =>
    console.log(responseDetails) # {statusCode: 401, headers: ['location': 'https://google.com/']} etc
  gotData: (data) =>
    console.log(data) # Node Buffer<...>
    console.log(data.toString()) # "the data"
  gotEnd: =>
    # Do some magic
```
All those events I used above are already emitted by the `request` library and can be easily emitted by a personal one too. and by using this structure, You can check if the user's provided argument is a stream and listen to those methods automatically, otherwise wait for the user to trigger them themselves, IMO that would simplify it a lot.

**Comment by frozeman** [comment]
@deepak1556 any time to look into this again? :heart:

**Comment by deepak1556** [comment]
@frozeman not sure, you could open a new issue to track this need. Someone interested might pick it up before i can :)

**Pull request closed without merging**
