### PR TITLE
Upgrade to Chrome 49

### PR DESCRIPTION
**Pull request by zcbenz**
Debug build compiles on:
* [x] OS X
* [x] Linux
* [x] Windows

Release build compiles on:
* [x] OS X
* [x] Linux
* [x] Windows

Tests passing on:
* [x] OS X
* [x] Linux
* [x] Windows

Features check list:
* [x] devtools
* [ ] Pepper Flash
* [ ] Widevine
* [ ] printing

Merge:
* [x] https://github.com/atom/libchromiumcontent/pull/175
* [x] https://github.com/atom/brightray/pull/200

### CODE REVIEW

**Comment by ZakariaRidouh** [comment]
What are some of the changes and improvements that this PR brings?

**Comment by MrSaints** [comment]
Great job @zcbenz ! Thank you.

**Comment by kamesh-a** [comment]
Cool @zcbenz Thank you.

**Comment by z-ax** [comment]
Finally, thanks! Most of ES6 without preprocessors. Waiting for the next release! :)

**Comment by kevinsawicki** [comment]
Awesome work @zcbenz @deepak1556 @paulcbetts :arrow_up: :four: :nine: :tada:

**Pull request merged**
