### PR TITLE
protocol: wrapping HttpJobFactory with a default protocol handler to intercept

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes https://github.com/atom/electron/issues/542

Need some clarification on how useful is this interceptor api, is there any wide use case for it to be present ? If its just offline scenario, wont service workers help out.. ?

### CODE REVIEW

**Comment by zcbenz** [comment]
The [built-in protocols](https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_request_job_manager.cc&sq=package:chromium&type=cs&l=32&rcl=1431300796) also include `https`, `ws` and `wss`, we should probably override all of them.

**Comment by zcbenz** [comment]
> Need some clarification on how useful is this interceptor api, is there any wide use case for it to be present ? If its just offline scenario, wont service workers help out.. ?

I think users are only using it for debugging purpose.

**Comment by deepak1556** [comment]
> The built-in protocols also include https, ws and wss, we should probably override all of them.

Sure , just wanted confirmation on the usefulness of this api :)

**Comment by deepak1556** [comment]
@zcbenz fixed.

**Comment by zcbenz** [comment]
Thanks!

**Pull request merged**
