### PR TITLE
[WIP] Convert from CoffeeScript to JavaScript

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull request migrates all of the CoffeeScript source files to JavaScript.

:chart_with_upwards_trend: CoffeeScript was great when this project started, but many of the best parts of it are now in ES6 and available out of the box in Electron. See [this blog post](http://blog.atom.io/2016/01/07/latest-v8-chromium-features.html) for some examples.

:coffee: The JavaScript files in this pull request were generated using CoffeeScript `1.10.0`.  A second pass will be made in a follow-up pull request to reformat the JavaScript and draft a new styleguide. This is done to minimally disrupt any open or soon to be opened pull requests that may touch the existing `.coffee` files.

:memo: The comments have been retained by first migrating all the `#` comments to `###` which were then compiled to `/* */` style comments in the JavaScript.

:dart: The goal is to make Electron as approachable as possible and also to have its source code reflect the capabilities of the V8 version being used.

### Changes to be made in subsequent pull requests

  - Cleanup accidental `return` statements
  - Cleanup comment formatting
  - Cleanup variable scoping
  - Remove CoffeeScript helpers like `extend`, `slice`, and `indexOf`
  - Use `let` and `const` appropriately
  - Use arrow (`=>`) functions

### CODE REVIEW

**Comment by lukeapage** [comment]
woop to this :+1:

**Comment by kamesh-a** [comment]
:+1:

**Comment by bennyn** [comment]
Keep going' :+1: :sunglasses:

**Comment by zcbenz** [comment]
:+1:

**Comment by stevemao** [comment]
I'm so happy for this change :smile:

**Pull request merged**
