### PR TITLE
Add MAS build

### LINKED ISSUE #249: Mac App Store
first of all thanks for open sourcing atom(-shell). It looks very interesting.

We currently have a chrome packaged app in the chrome web store and were looking at using node-webkit to package the app for the mac app store. Is this possible with atom-shell as well? I ask this because this was an issue for node-webkit at first, since it used private mac os apis:
https://github.com/rogerwang/node-webkit/issues/936

Thanks

### PR DESCRIPTION
**Pull request by zcbenz**
This PR adds a new MAS build which removes usages of private API calls of OS X and can be published to Mac App Store.

* [x] Disable auto updater
* [x] Disable crash reporter
* [x] Remove private API calls in libchromiumcontent
* [x] Verify it can be published to Mac App Store
* [ ] Add a guide on using MAS build

Fixes #249.

### CODE REVIEW

**Comment by lipis** [comment]
:100:

**Comment by YuriSolovyov** [comment]
Shouldn't such build be a default one for mac?

**Comment by zcbenz** [comment]
> Shouldn't such build be a default one for mac?

To be compatible with Mac App Store we have to disable some important features, I'll give a list of the features not available in MAS build as a part of this PR.

**Comment by fscherwi** [comment]
:+1:

**Comment by hankbao** [comment]
:+1:

**Comment by rhysd** [comment]
:+1:

**Comment by zcbenz** [comment]
I have successfully uploaded the MAS build to iTunes Connect and passed Apple's private APIs usage check, but currently we are in the middle of upgrading our OS X build machines and I'm not able to provide a public build for now.

I'm merging this branch since the mas build doesn't affect our normal build, a public build and guides on uploading to Mac App Store will be provided in other pull requests.

screen shot 2015-10-14 at 12 00 24 pm

**Comment by hankbao** [comment]
:+1:  Cool.

**Comment by joshaber** [comment]
:metal:

**Comment by callumlocke** [comment]
👏

**Comment by herrmannplatz** [comment]
:100:

**Comment by kevinsawicki** [comment]
:+1: This is so awesome

**Comment by imskull** [comment]
:+1:

**Comment by kamesh-a** [comment]
:+1:

**Comment by lipis** [comment]
Do we have the public builds for MAS somewhere?! Can't find them..

**Comment by KevinMartin** [comment]
> a public build and guides on uploading to Mac App Store will be provided in other pull requests.

**Comment by behrangsa** [comment]
:100:

**Comment by lipis** [comment]
#3108

**Pull request merged**
