### PR TITLE
Adding support to write RTF to clipboard.

### PR DESCRIPTION
**Pull request by Vj3k0**
Created `writeRtf` method and added support to `write` for object with rtf property. Also added method to documentation (only in english).

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Would you mind adding some specs for this to `spec/api-clipboard-spec.js`?

**Comment by Vj3k0** [comment]
I pulled the changes and now they are causing build to fail (maybe should've done this in separate branch not master).
How do I solve it?

**Comment by kevinsawicki** [comment]
> I pulled the changes and now they are causing build to fail

Do you mean the Travis build or your local build? The Travis failures looks like it had trouble connecting to NPM so it would be unrelated to your changes and just a fluke, sorry about that.

**Comment by Vj3k0** [comment]
Yep meant Travis. Ok then. Cheers!

**Comment by kevinsawicki** [comment]
Thanks so much for contributing this :+1: :ship:

**Comment by Vj3k0** [comment]
Thanks m8, glad to be of help!

**Pull request merged**
