### PR TITLE
Emit verify-certificate only when default verifier fails

### PR DESCRIPTION
**Pull request by zcbenz**
The only use case of `verify-certificate` is to allow untrusted certificates, so we don't need to emit it when the certificate is trusted.

### CODE REVIEW

**Comment by steelbrain** [comment]
IMHO, this defeats the purpose of the API. #3318 is no longer resolved

**Comment by zcbenz** [comment]
@steelbrain What is the use case of manually verifying a trusted certificate?

**Comment by steelbrain** [comment]
@zcbenz There are certain orgs that don't trust all the CAs, they trust just a few and often pin those verified certificates. My original use case was a similar one

**Comment by zcbenz** [comment]
@steelbrain That's interesting, I'll come with a solution.

**Pull request merged**
