### PR TITLE
Update power-monitor.md

### PR DESCRIPTION
**Pull request by guatedude2**
Updated docs in power-monitor to reflect windows only events

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thanks for catching that! Stupid request: Could you make the `windows` italic (using `*windows*`)? That's how it is in the other docs ;-)

**Comment by guatedude2** [comment]
i sure can

**Comment by kevinsawicki** [comment]
:+1: Thanks for this

**Comment by guatedude2** [comment]
No problem!

**Pull request merged**
