### PR TITLE
Docs: Update korean docs as upstream

### PR DESCRIPTION
**Pull request by preco21**
* Fix typos
* Update as upstream
* Small changes

### CODE REVIEW

**Comment by ArekSredzki** [comment]
Please squash your commits and rename the PR to be more reflective of the changes.
Ex: `Update Korean Documentation Translations`

**Comment by preco21** [comment]
@ArekSredzki Thank you for feedback!  I'll change it.

**Comment by ArekSredzki** [comment]
:+1:

**Comment by ArekSredzki** [comment]
Also, I'm confused as to what you mean by "as upstream". Do you mean "to match upstream"? :)

**Comment by preco21** [comment]
Yup I mean just match korean docs as `upstream`.

**Comment by ArekSredzki** [comment]
okay, and don't forget to squash those commits, there's no need to pollute the git history for a couple read me changes :)

**Comment by preco21** [comment]
Of course! I'll apply that!

**Comment by zcbenz** [comment]
Committed as  4c45c80, thanks!

@preco21 Next time before you started translation, you might try running `git reset --hard atom/master` under your local repo, which will force your repo to get updated with upstream.

**Comment by preco21** [comment]
@zcbenz Thank you for cool advice! I'll try it!

**Comment by ArekSredzki** [comment]
@preco21 Also, if changes occur as you're working on something, try [rebasing](https://www.atlassian.com/git/tutorials/rewriting-history/) rather than merging in the upstream :)

**Comment by preco21** [comment]
@ArekSredzki Thank you for advice :+1:

**Pull request closed without merging**
