### PR TITLE
Add info on how to debug from 0.30 onwards

### PR DESCRIPTION
**Pull request by lukeapage**
derived from help on #3378

### CODE REVIEW

**Comment by zcbenz** [comment]
Looks good to me. :+1:

**Comment by 3y3** [comment]
Latest version of `v8-debug` and `v8-profiler` stores all prebuilt binaries in npm, so when you install this packages you are compatible with all platforms for node 0.12.* , 4.*, 5.*
It may be reasonable to add `electron` in TravisCI and Appveyor build matrix to avoid recompilation here.

**Comment by lukeapage** [comment]
@3y3 sounds good and will simplify the process for many people.

**Comment by 3y3** [comment]
Do you have any example of repository, which work with electron in TravicCI?

**Comment by lukeapage** [comment]
Not off the top of my head.. Sure they exist though. What do you want it for?

**Pull request merged**
