### PR TITLE
Fix broken/outdated link and push up the version

### PR DESCRIPTION
**Pull request by HR**

### CODE REVIEW

**Comment by HR** [comment]
Can it be 
```bash 
--target=$(electron -v | sed s/\v//g)
``` 
instead of an explicit value? (doesn't need to be updated)

**Comment by zcbenz** [comment]
:+1:

**Comment by zcbenz** [comment]
> Can it be
> --target=$(electron -v | sed s/\v//g)
> instead of an explicit value? (doesn't need to be updated)

It won't work for Windows users, we should probably write a script to update the versions in documents.

**Comment by HR** [comment]
Yeah but different users maybe using different versions. And may not be able to update (significant API changes)

**Pull request merged**
