### PR TITLE
Switch to GTK3

### LINKED ISSUE #2927: Consider replacing GTK2 w GTK3 in Linux builds
Google recently added a "use_gtk3" build flag to Chormium - export GYP_DEFINES="$GYP_DEFINES use_gtk3=1"﻿.

I think most end-users on GTK3 desktops would prefer to use modern widgets. It might be too early to add it as a default, but eventually it be nice.

Video of Chromium 47 w gtk3:
https://www.youtube.com/watch?v=TJidbdaHCYc

This somewhat relates to an old issue I opened up:
https://github.com/atom/electron/issues/765

### PR DESCRIPTION
**Pull request by flying-sheep**
fixes #2927

### CODE REVIEW

**Comment by thomasjo** [comment]
Does the presence of this flag degrade gracefully? In other words, does this cause any problems for users on GTK2 systems? If it causes problems, we will have to implement this differently prevent *Breaking the Entire World*™.

**Comment by flying-sheep** [comment]
well, after switching, electron will depend on GTK3 and and no longer legacy GTK2.

what do you mean by GTK2 system?

1. all systems GTK desktop environments including the GNOME2 fork MATE are GTK3 based
2. a system without $library installed will require you to install $library to use a software depending on $library

**Comment by thomasjo** [comment]
We should not force every project that uses Electron to enforce their users to installing GTK3 just because they updated the version of Electron they built their app on...

While we can make a change like this, keep in mind this is a breaking change unless the feature flag degrades gracefully. Unless someone can confirm the graceful degradation, I'm opposed to this change.

The alternative here is to make this flag opt-in.

**Comment by flying-sheep** [comment]
well, you’re simply follow what chromium does. if chromium changes one of its dependencies, will you freeze the chromium version because of that?

fwiw, @zcbenz said in #2927:

> Sounds good to me after we upgraded to Chrome 47.

it will look better and integrate into the system look, have a better file picker and so on. it’s a big usability win, having support for new UI features like hi-res displays, scrolling behavior, …

**Comment by thomasjo** [comment]
> fwiw, @zcbenz said in #2927:
> 
> Sounds good to me after we upgraded to Chrome 47.

You removed the context in which he added that comment though;

> [..] I think most end-users on GTK3 desktops would prefer to use modern widgets. It might be too early to add it as a default, but eventually it be nice.

And that is essentially what I'm saying as well. Enabling this by default is likely a bad idea unless the flag degrades gracefully. If this was a stable and baked feature on the Chromium side, it would not have a feature flag. @zcbenz and others might disagree with me, but I think it's irresponsible to add this by default since it will (in all likelihood) cause problems for users on GTK2 systems (MATE, LXDE, Xfce, etc) without making it dead-easy to opt-out of this.

Making this opt-in for the time being is the only sensible approach in my opinion.

**Comment by flying-sheep** [comment]
good points, except that i’m extremely sure that people who don’t use *any* GTK3 thing also won’t use electron, and both MATE and Xfce use GTK3. (while LXDE is switching to Qt)

i just can’t see a single person who’d use exclusively LXDE-apps, chromium, and electron apps (everything else already switched to GTK3). LXDE stuff is for extremely memory-limited systems, exactly where chromium and electron *don’t* fit.

**Comment by paulcbetts** [comment]
We should do whatever Chrome 47 does, I'm :+1: on this change in general, nobody these days has GTK2 installed but not GTK3

**Comment by thomasjo** [comment]
> [..] nobody these days has GTK2 installed but not GTK3

If that's the case across the general end-user base for Electron apps, then I'm :ok: with this.

> We should do whatever Chrome 47 does

But that's the thing, GTK3 support is hardly stable yet. The Chromium folks are (or at least were last I checked) using deprecated GTK APIs and what not.

Well, I guess worst case we can always revert this if all hell breaks loose, hehe :smiling_imp: 
Let's leave the final verdict up to @zcbenz.

**Comment by flying-sheep** [comment]
OK! i didn’t know that stability might be a problem, but generally chromium tests well and people already included [GTK3 theme integration](https://bugs.chromium.org/p/chromium/issues/detail?id=132847), which might indicate sufficient stability.

i researched a bit and it seems that the use of deprecated APIs [is intentional](https://chromium.googlesource.com/chromium/src.git/+/c694003c15dc6af21b453febd1463c5394c98c9e).

**Comment by zcbenz** [comment]
The `use_gtk3` flag is only meaningful under Chromium's side, to enable GTK3 we need to enable it in libchromiumcontent first, and then change the link settings in Electron.

Chrome is not using GTK3 by default, unless your distribution manually enabled the flag for the package. For when will Chrome switch to use GTK3, you can track this issue: https://crbug.com/79722, it is quite close but not yet done.

I'm closing this since it is actually not doing anything.

**Comment by flying-sheep** [comment]
ah, OK!

but i’m still lost as i know nothing about the inner workings here.

will follow up in the issue.

**Pull request closed without merging**
