### PR TITLE
Add session module

### LINKED ISSUE #959: Multi-session support for BrowserWindow and webview
When I use a webview and log in to a website (let's say github) it appears the session/cookie information is lost after restarting the application. Is there a way to enable this on the webview?

### PR DESCRIPTION
**Pull request by zcbenz**
```markdown
### session.fromPartition(partition)

* `partition` String

Returns a new `Session` instance from `partition` string.

If `partition` starts with `persist:`, the page will use a persistent session
available to all pages in the app with the same `partition`. if there is no
`persist:` prefix, the page will use an in-memory session. If the `partition` is
empty then default session of the app will be returned.

### session.defaultSession

Returns the default session object of the app.
```

Fix #959.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why not `session.fromPartition(partition, {persist: true})`? Using a prefix is kinda awkward unless there's a reason for it being there that I'm missing.

The docs doesn't really explain what a `partition` is? If it's just a word choice, I would go with `id` or `name` instead.

**Comment by zcbenz** [comment]
This is to match the style of the `partition` option of `BrowserWindow` and `webview`, it would surprise users if they don't use the same format.

The idea of `partition` comes from Chrome's [webview tag](https://developer.chrome.com/apps/tags/webview#partition), it is a concept that has already been widely used so I think it should be more easy to understand. I agree we should explain more about what is a `partition` in the document.

**Comment by sindresorhus** [comment]
Oh, ok. Didn't realize it was an already existing concept. Linking to the webview tag partition docs would be a start.

**Comment by spolu** [comment]
\o/

**Comment by mmahalwy** [comment]
@zcbenz I have tried many times to read the docs but it doesn't make sense. I get why `fromPartition` is useful but there is a disconnect to how to even output or save a partition. I think this is purposed to solve the 'where do I save my session or user info?' question but still unsure how to use this...

**Pull request merged**
