### PR TITLE
api/accelerator.md and api/process.md translated to pt-Br

### PR DESCRIPTION
**Pull request by nicholasess**

### CODE REVIEW

**Comment by zcbenz** [comment]
Can you remove the `-pt-BR` suffix in filenames? We no longer add that after we have moved the translations to a new folder.

**Comment by nicholasess** [comment]
Why failed the commit about remove old files?

**Comment by jonatasfreitasv** [comment]
Hi @nicholasess, change link in README (pt-br) and review your created documents, have problems, you used automatic translator. cc @zcbenz

**Comment by nicholasess** [comment]
Just for some words, if you found errors, give me a correct translation :)

**Comment by jonatasfreitasv** [comment]
in later i review your documents

**Comment by jonatasfreitasv** [comment]
Change path to ```api/process.md```

**Comment by jonatasfreitasv** [comment]
Commit have a conflicts, your fork version is old, fallow this tutorial to sync your fork. *[How to sync a fork](https://help.github.com/articles/syncing-a-fork/)*

**Comment by nicholasess** [comment]
Thanks for the help @jonatasfreitasv

**Comment by nicholasess** [comment]
I don't understand the why the travis doesn't accept the commit, i'll close the PR and send a new PR with corrections.

**Pull request closed without merging**
