### PR TITLE
Add link to `awesome-electron`

### PR DESCRIPTION
**Pull request by kevva**
Good list of really cool applications using `electron`.

### CODE REVIEW

**Comment by arthurvr** [comment]
Besides from awesome apps built using electron, the list also contains some really useful resources and tools. :+1:

**Comment by zcbenz** [comment]
Can you add it to the list in https://github.com/atom/electron.atom.io? It already has a list of open source apps based on Electron, having two places for that seems confusing to me.

**Comment by sindresorhus** [comment]
The website has a nice preview, but I doubt you want to show every Electron app there. There's going to be a lot of apps in a year. [The list](https://github.com/sindresorhus/awesome-electron) also has other useful resources in addition to apps.

**Comment by zcbenz** [comment]
It sounds reasonable to me, should we also add #1684 to `awesome-electron`?

**Comment by paulcbetts** [comment]
:+1: to `awesome-electron` link

**Pull request merged**
