### PR TITLE
Make clear creating a signed app for Mac is not free

### PR DESCRIPTION
**Pull request by maxcnunes**
I spent sometime configuring the auto updater for Mac apps in my application. And just after that I tried to create my apple certificate.

Maybe if it was described somewhere I didn't have spent time on this.

### CODE REVIEW

**Comment by paulcbetts** [comment]
Distributing Mac apps in any way is not free because of Gatekeeper, you have to have a Developer ID: https://developer.apple.com/support/compare-memberships.

**Comment by maxcnunes** [comment]
Yeah. I didn't know that. Maybe including it in the docs will help other people avoiding the same mistake.

**Comment by zcbenz** [comment]
If you don't care about the warnings created by Gatekeeper, you can just sign your app with a self-authorized certificate, which works with autoUpdater. You also have to add instruction for users on how to ignore the security warning to open your app though, many hobby apps are going this way.

If you are submitting to MAS, you can not use the autoUpdater, the apps are updated in other ways.

Anyway I added a note on the money thing in the docs.

**Comment by maxcnunes** [comment]
Cool. I think this enough.
Thanks

**Comment by maxcnunes** [comment]
@zcbenz may be including your comment somewhere in the docs could help a lot. This way people would know that actually is possible use the auto updater with a self authorized certificate.

**Pull request closed without merging**
