### PR TITLE
Add "black background?" to FAQ

### LINKED ISSUE #4937: electron-v0.37.3-win32-ia32 webpage background color is black
* Electron version:electron-v0.37.3-win32-ia32
* Operating system:windows 10 x64

untitled

### PR DESCRIPTION
**Pull request by felixrieseberg**
Closes #4937

### CODE REVIEW

**Comment by zeke** [comment]
Thanks @felixrieseberg! Is your background black because your specific desktop wallpaper is black? If so, maybe the question should be "Why is my app's background transparent?"

It might also be nice to drop in a little code snippet illustrating a very basic way to set the background color:

```html
<style type='text/css'>
  html {
    background: white;
  }
</style>
```

**Comment by felixrieseberg** [comment]
Thanks @zeke, good call - added!

**Comment by zeke** [comment]
:sparkles: :computer:  :sparkles:

**Comment by deepak1556** [comment]
:+1:

**Pull request merged**
