### PR TITLE
override: set window.opener to null for webview

### LINKED ISSUE #1866: [Bug] window.opener is not null in webviews
In webviews, the window.opener is not null.
I get a broken BrowserWindowProxy instead of null. Calling window.opener.postMessage results in an error in any case.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1866

### CODE REVIEW

**Comment by paulcbetts** [comment]
You could make this do `ipc.sendToHost` maybe?

**Comment by deepak1556** [comment]
Should `webview` have a concept of `window.opener` , like it doesnt have a `BrowserWindow` ?

**Comment by paulcbetts** [comment]
> Should webview have a concept of window.opener , like it doesnt have a BrowserWindow

Yeah, I could go either way, just trying to think of what would be useful for developers if they're trying to do something like frame an OAuth dialog in a `dialog` tag

**Comment by deepak1556** [comment]
Yeah thats quite a use case, but it will violate the spec
```
window.opener
Returns a reference to the window that opened this current window.
```
maybe when we have detachable webviews ? @zcbenz thoughts ?

**Comment by zcbenz** [comment]
:+1:

**Comment by lucidNTR** [comment]
sorry, if im too stupid, but what is the state of using "opene"r with webviews? does the merge mean its usable now or just that it is set to null now? I try to use a webview as an oauth dialog and dont get it to work... ( electron 0.30.1)

**Pull request merged**
