### PR TITLE
Add arm build

### LINKED ISSUE #366: ARM build
Is there a way to cross/compile atom-shell for ARM based computers?

### PR DESCRIPTION
**Pull request by zcbenz**
This PR adds support for cross compiling for arm target.

Closes #366.

### CODE REVIEW

**Comment by zcbenz** [comment]
Currently it is blocked by the lack of libnotify development headers in the sysroot image provided by Chromium, so we have two options here: 1) provide our own sysroot image or 2) disable libnotify support in arm build. I'll try the first way first.

**Comment by zcbenz** [comment]
Another thing is there are actually two versions of arm target here, one is armel(version 6), the other is armhf(version 7), I will only provide armhf build since it is powerful enough to run electron and it is widely used.

**Comment by luan007** [comment]
this looks great :+1: , do we need to compile libchromiumcontent manually or it's just fully automatic?

**Comment by zcbenz** [comment]
@luan007 It is fully automatic like the other targets.

**Comment by luan007** [comment]
@zcbenz Thank you! Our Build is stuck at an unauthorized message during init_download from amazons3(contentlib), maybe it will work after the merge?

**Comment by zcbenz** [comment]
@luan007 This branch is still WIP, you should wait until it gets merged.

**Comment by luan007** [comment]
thanks a lot, will stay in tuned

**Comment by zcbenz** [comment]
We now can successfully create distribution for arm target, and have both ia32 and arm targets building on travis ci.

**Comment by luan007** [comment]
amazing!

**Comment by jlord** [comment]
:sparkles: :sparkles: :sparkles: :sparkles: :sparkles: So great! 

I should have read this thread earlier, before trying to get Atom going with it myself—this means the next release will include the ARM builds so when building Atom it will find the right Electron?

**Comment by miladsajjadi** [comment]
I am beginner in electron packager. i want to build my project for target arch arm v7. what should i do?
running this:
> electron-packager . MYPROJECT --platform=linux --arch=armhf --overwrite --prune
will cause in:
Unsupported arch armhf; must be one of: ia32, x64

my host machine is windows. does electron packager add support for arm build?

**Comment by jujubetz** [comment]
Same as miladsajjadi here

**Comment by jlord** [comment]
@miladsajjadi @jujubetz The current version of ARM that Electron uses is `armv7`. There is an open issue to name it more precisely #2343.

**Comment by jujubetz** [comment]
Thanks @jlord. 👍

**Comment by nathanjdawson** [comment]
Sorry to resurrect such an old pull request, but I noticed @jujubetz and @miladsajjadi are (or were) on the same path I'm currently heading down, using electron-packager to compile for Raspberry Pi - I interpreted @jlord's answer as changing the arch=armv7 - but this is definitely not the case. Pinging people here to hopefully find some definitive answers to my scenario.

**Comment by jujubetz** [comment]
Hey @nathanjdawson I think there is no "easy" way to "pack" a electron app to raspberry pi now... I'm now doing this: clone my electron app from git, using npm install (it download the electron arm release automatically (https://github.com/electron/electron/releases)) and then i did a script that start my app by running: 

> /home/pi/myapp/node_modules/electron-prebuilt/dist/electron /home/pi/myapp .

It is not the best solution but it's working now.

**Comment by nathanjdawson** [comment]
@jujubetz thanks so much for the reply! From what I could find an ARM addition to electron-packager is not fair off, considering the github issues thread it's only waiting on a naming convention change. Hope your project is going well, again thank you for the answer!

**Pull request merged**
