### PR TITLE
updated the devtools documentation 

### PR DESCRIPTION
**Pull request by pdoh00**
Indicate how to get the basic chrome devtools in an electron application.

### CODE REVIEW

**Comment by brunze** [comment]
@pdoh00 Just the answer I was looking for! Thank you! :smiley:

**Comment by zcbenz** [comment]
Can you move this to quick-start.md? It is actually not related to devtools extension.

**Comment by pdoh00** [comment]
Yes. No problem.

**Comment by pdoh00** [comment]
@zcbenz My git-fu is pretty bad.  Sorry about the commit history.  Is this update to the quick-start how you would like it?  If there are some more changes you would like please let me know.

**Comment by zcbenz** [comment]
Thanks, I have pushed the change to 71ee864.

**Pull request closed without merging**
