### PR TITLE
Docs: desktop integration: OS X supports progress bar

### PR DESCRIPTION
**Pull request by adam-lynch**

### CODE REVIEW

**Comment by zcbenz** [comment]
On Linux only Unity desktop environment supports progress bar, we need to make it clear.

I think you can just add a paragraph on how OS X shows the progress bar.

**Comment by adam-lynch** [comment]
Ok willd

**Comment by adam-lynch** [comment]
OK will do

**Comment by zcbenz** [comment]
Closed in favour of 5f95fea.

**Pull request closed without merging**
