### PR TITLE
Added korean translations for BrowserWindow

### PR DESCRIPTION
**Pull request by deopard**

### CODE REVIEW

**Comment by deopard** [comment]
I don't understand. Why did the test fail when I just added one markdown file?

**Comment by zcbenz** [comment]
The test is a bit flaky, the change itself is fine.

Also I think the filename should be `web-contents.md` instead of `browser-window.md`?

**Comment by preco21** [comment]
And should be `vendor/brightray` is excluded.

**Comment by zcbenz** [comment]
Committed at https://github.com/atom/electron/commit/099da729c7ad19755b69f50b04a33ea6167e889d.

**Pull request closed without merging**
