### PR TITLE
app: adding focus/blur events

### LINKED ISSUE #1985: window focus/blur event on the app instance
I would be useful to have a focus/blur window event on the `app` instance. I can already subscribe to the focus/blur event on each window and act accordingly, but it would be a lot nicer to just be able to do:

```js
var app = require('app');

app.on('focused-window', function (focusedWindow) {
  doSomethingWithTheFocusedWindow(focusedWindow);
});
```

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1985

### CODE REVIEW

**Comment by thesbros** [comment]
There's a typo, the event is called `blured-window`, it should be `blurred-window`.

**Comment by zcbenz** [comment]
I think we can simply implement it with just 2 lines?

```coffeescript
BrowserWindow::_init = ->
  ...
  @on 'focus', (event) =>
     app.emit 'browser-window-focus', event, this
  ...
```

And I think `browser-window-focus` should be a better event name.

**Comment by deepak1556** [comment]
@zcbenz yeah :(

**Comment by deepak1556** [comment]
Fixed, thanks!

**Comment by zcbenz** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1: Thanks @deepak1556 :)

**Pull request merged**
