### PR TITLE
Fixing link to web contents from ipcMain

### PR DESCRIPTION
**Pull request by adam-lynch**
This will fix the HTML docs but seems to break the markdown docs. I'm not sure how the HTML docs are generated and if the links are changed somehow. I'll submit this anyway.

### CODE REVIEW

**Comment by zcbenz** [comment]
It seems to be a bug of the HTML generator used by https://github.com/atom/electron.atom.io, this change would break the markdown renderer of github.com.

I think the only workaround is to replace all `[webcontents-send]` with `web-contents.md#webcontentssendchannel-arg1-arg2-`.

**Comment by adam-lynch** [comment]
@zcbenz yeah I was unsure how the HTML was actually generated. 

>I think the only workaround is to replace all [webcontents-send] with web-contents.md#webcontentssendchannel-arg1-arg2-.

Do you mean remove all links with variables and replace them with the actual URL? If not then, I'm not sure what you mean because that (.md) URL looks the same what it is right now (before my PR).

**Comment by zcbenz** [comment]
> Do you mean remove all links with variables and replace them with the actual URL?

Yeah that's what I meant.

**Comment by adam-lynch** [comment]
Ok @zcbenz I've updated this PR. I couldn't find the HTML generation documented anywhere, maybe that would be a good idea? So people could test their changes locally.

**Comment by zcbenz** [comment]
The whole document site is open sourced at https://github.com/atom/electron.atom.io, you have build it locally.

**Comment by adam-lynch** [comment]
:+1:

**Pull request merged**
