### PR TITLE
Replace Mac with OS X

### PR DESCRIPTION
**Pull request by bureken**

### CODE REVIEW

**Comment by paulcbetts** [comment]
I don't think we need these trivial changes

**Comment by OlsonDev** [comment]
Would be inconsistent to not take them consideringhttps://github.com/atom/electron/pull/3115

**Comment by paulcbetts** [comment]
Sure, until 3mo from now when someone gets a bee in their bonnet and decides to replace all of the "OS X" occurrences with "Mac"

**Comment by zcbenz** [comment]
@paulcbetts During previous documentation improvements we decided to standardize the terms, and using "OS X" instead of "Mac" is one of them.

**Comment by sindresorhus** [comment]
@paulcbetts The official OS name is `OS X`. Mac is the hardware. Correctness and consistency is important.

2015-11-04 at 12 58

**Comment by thomasjo** [comment]
> @paulcbetts The official OS name is OS X. Mac is the hardware. Correctness and consistency is important.

I wholly agree with this.

**Pull request merged**
