### PR TITLE
Upgrade to Chrome 47

### PR DESCRIPTION
**Pull request by zcbenz**
Debug build compiles on:
* [x] OS X
* [x] Linux
* [x] Windows

Release build compiles on:
* [x] OS X
* [x] Linux
* [x] Windows

Tests passing on:
* [x] OS X
* [x] Linux
* [x] Windows

Merge:
* [x] https://github.com/atom/libchromiumcontent/pull/163
* [x] https://github.com/atom/brightray/pull/182

### CODE REVIEW

**Comment by lipis** [comment]
Is there any possible ETA for this? Even if it's very very rough... :)

**Comment by LukeStebbing** [comment]
Will you also be updating atom/node to V8 4.7? It's [not clear](https://github.com/nodejs/node/pull/4106) whether it'll be in a Node.js release before v6.0.0 next April.

**Comment by paulcbetts** [comment]
@lipis Generally once the Electron PR is up (i.e. this one you're looking at!) you can build it yourself to test

**Comment by lipis** [comment]
for production we prefer the release versions.. so that's why I'm asking.. don't want to rush anything :) just curious if it's days, weeks, months :)

**Comment by lipis** [comment]
oki. that was fast.. :) thanks @zcbenz

**Comment by paulcbetts** [comment]
User Agent still reports Chrome 45, which is Odd

**Comment by paulcbetts** [comment]
Also, according to https://chromestatus.com/features, this code should be valid

```
f = new DOMException();
```

But throws in master

**Comment by lipis** [comment]
@paulcbetts they don't support naked `https` https://www.chromestatus.com/features

**Pull request merged**
