### PR TITLE
:memo: Add missing `httpreferer` option doc.

### PR DESCRIPTION
**Pull request by hokein**
The PR #801 forgot to update the doc.

\cc @frankhale

### CODE REVIEW

**Comment by deepak1556** [comment]
can you also doc the `userAgent` option .

**Comment by frankhale** [comment]
:+1: Thanks @hokein

**Comment by hokein** [comment]
@deepak1556 
Done :+1:

**Comment by zcbenz** [comment]
Can you rename the option names to `httpReferer` and `userAgent`? It has not been documented yet so a rename should be OK.

**Comment by hokein** [comment]
Done.

**Comment by zcbenz** [comment]
The calls in webview also needs to be changed.

**Comment by hokein** [comment]
@zcbenz Done.

**Comment by zcbenz** [comment]
:+1:

**Pull request merged**
