### PR TITLE
webFrame: api to make scheme bypass CSP

### PR DESCRIPTION
**Pull request by deepak1556**
Refs https://github.com/atom/electron/issues/2223

### CODE REVIEW

**Comment by paulcbetts** [comment]
Is there any reason to not just do this when `registerSchemeAsSecure` is called?

**Comment by deepak1556** [comment]
Mostly because of the api name, avoiding mixed content warning and bypassing csp are different things. Wont users find the api description a bit confusing now ?

```
Registers the `scheme` as secure scheme and the resouces can be loaded
regardless of page's Content Security Policy
```

would separate api be better or different api name ? Really dont like securing a scheme to do both.

**Comment by deepak1556** [comment]
have added as a separate api `registerUrlSchemeAsBypassingCsp`

**Comment by zcbenz** [comment]
Thanks!

**Comment by linonetwo** [comment]
For people googled here, this is chagned to `protocol.registerSchemesAsPrivileged`

Example to bypass http csp:

```
protocol.registerSchemesAsPrivileged([
  { scheme: 'http', privileges: { standard: true, bypassCSP: true, allowServiceWorkers: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
  { scheme: 'https', privileges: { standard: true, bypassCSP: true, allowServiceWorkers: true, supportFetchAPI: true, corsEnabled: true, stream: true } },
  { scheme: 'mailto', privileges: { standard: true } },
]);
```

**Pull request merged**
