### PR TITLE
explicitly document that file path for nativeImage need to be normalized.

### PR DESCRIPTION
**Pull request by simpzan**
explicitly document that file path for nativeImage need to be normalized.
[ci skip]

### CODE REVIEW

**Comment by zcbenz** [comment]
Can you give an example of what problem would be caused by an unnormalized path? I would rather fix the problem in code instead of asking users to do it themselves.

**Comment by simpzan** [comment]
when the path is unnormalized, like `/Users/simpzan/js/autoshadow/testbed/app/../assets/IconTemplate.png`, there will be exception:
```
Uncaught Exception:
TypeError: Error processing argument -1.
    at TypeError (native)
    at EventEmitter.setupTray (/Users/simpzan/js/autoshadow/testbed/app/app.js:15:13)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```
see the attached demo package.
[testbed.zip](https://github.com/atom/electron/files/136189/testbed.zip)

**Comment by YuriSolovyov** [comment]
maybe it would be better to normalize it anyway under the hood? could it break anything?

**Comment by zcbenz** [comment]
I think we should just always normalize the path, it won't break anything as far as I know.

@simpzan Can you create a new issue for this?

**Comment by simpzan** [comment]
@zcbenz issue created here. https://github.com/atom/electron/issues/4574

**Pull request closed without merging**
