### PR TITLE
Use require('ipc-renderer') instead

### PR DESCRIPTION
**Pull request by softage0**
Use require('ipc-renderer') instead of require('electron').ipcRenderer in docs
https://github.com/atom/electron/issues/3577

### CODE REVIEW

**Comment by zcbenz** [comment]
Thanks for this but `require('electron').ipcRenderer` is the correct one, the original issue was using docs with the wrong version of Electron.

**Comment by softage0** [comment]
I'm using "electron-prebuilt" version 0.35.1 and I have same issue.
Does it also use the different version of Electron?

**Comment by d9k** [comment]
`require('electron').ipcRenderer` doesn't work for me too

**Comment by gsantome** [comment]
I'm using electron prebuilt 0.36.3 and I'm having the same problem... this make me crazy... because if I remove electron-prebuilt i cant start the app... I need help with this.

Thanks

**Pull request closed without merging**
