### PR TITLE
Don't expose "global" when node integration is off

### LINKED ISSUE #2183: `global` object defined in webview
Hi,

I noticed that `global` object defined in the webview (it's reference to the `window`, but) it's different from regular browser "environment" where `global` object is undefined. And many libraries (primary UMD-type ones) make decision on which branch of code to execute based on the existence of `global` object. Which would lead to breakage of the page loaded into webview, or at least would produce different experience for the end user.

I did try to add "userland" fix for the issue, but it yelled at me :)

Added `preload` script for webview

```
process.nextTick(function(){ global = undefined; });
```

Result:
error

### PR DESCRIPTION
**Pull request by zcbenz**
Fix #2183.

### CODE REVIEW

**Comment by alexindigo** [comment]
Thanks. :+1:

**Comment by paulcbetts** [comment]
We should consider reverting this, this change actually is causing a ton of headaches:

1. You have a webview with a preload script
1. The preload script calls `require` to load some other code, which has a reasonable expectation that `global` will be defined
1. `global` gets yanked because of #2215 
1. Code that was previously working before now blows up because global is not defined

If you've got code that is reused between the browser process and preload script (like for logging, etc), you're kind of hosed because there is no `window` in browser, and no `global` in preload (of course, you can patch one back in, but it's a hack)

**Comment by alexindigo** [comment]
Should preload script expect nodejs things to work if node-integration is disabled?

**Comment by paulcbetts** [comment]
> Should preload script expect nodejs things to work if node-integration is disabled?

Yes, that is the only reason that we have preload scripts

**Comment by alexindigo** [comment]
Ok, and it's executed before things get cleaned up, so they don't get mixed with guest javascript, right?

**Comment by paulcbetts** [comment]
@alexindigo Exactly, so:

1. Preload script runs, includes everything it needs
1. node.js constants get removed (require, process, etc)
1. Page load happens

However, you can define objects that will end up in the page's global scope. If that page calls a method that uses `global`, we die. This is true of other node.js constants too (especially `process`), but `global` is one that bites particularly hard because in practice, most node.js libs end up grabbing references to things they need during `require`

**Comment by alexindigo** [comment]
Sounds like a leak to my ears. I mean we have webview with disabled node-integrations for a reason – third-party content, we can't trust. Allowing privileged modules to expose themselves like that is dangerous.

As fast solution I'd see something like a flag `keep-global` along with `node-integration`, or `cleanup-global` (`pretending-browser`).

Although it feels right to investigate (brainstorm) other solutions for community benefits.

For example, `preload.js` populate `exports` object with stuff it wants to expose to the guest content,
and when guest content is loaded, reset script would copy stuff from `exports` to the `window` object.

PS. When I was hacking around, I found it was somewhat annoying that reset script being executed within same tick as guest javascript. Not sure if it's something easy/hard to fix, but seems like separating those two would allow for better user-land hacks. I mean running things `process.nextTick` and knowing it will be executed before first line of the guest javascript, but after reset script is done (therefore within "browser" environment).

**Comment by zcbenz** [comment]
Since we are also removing `process`, I think it is impossible to make all node modules happy anyway, so I would rather keep consistency in this situation, e.g. removing both `process` and `global`.

**Pull request merged**
