### PR TITLE
Organize Documentation Translations

### PR DESCRIPTION
**Pull request by jlord**
Per https://github.com/atom/electron/issues/2524

This PR moves the translated docs into their own language specific directories:

```text
Electron
|_`docs`
|_`docs-translations`
   |_ `es`
   |_ `ko`
   |_ `jp`
```

I think the English version in the `docs` directory should be the one we publish to electron.atom.io. The language-specific docs are updated less regularly and will make the site much bigger so I think it is ok to leave them only in the repository, what do others think?

### CODE REVIEW

**Comment by OlsonDev** [comment]
Perhaps http://electron.atom.io/docs/ should have deep links (to repo folders) to the various translations on the homepage to enhance discoverability?

**Comment by jlord** [comment]
> deep links (to repo folders) to the various translations on the homepage

Oh yeah, good point :+1:

**Comment by zcbenz** [comment]
> The language-specific docs are updated less regularly and will make the site much bigger so I think it is ok to leave them only in the repository, what do others think?

It sounds good to me.

**Comment by LeMoussel** [comment]
Can you create dirtectory for FR translation?

**Comment by jlord** [comment]
@LeMoussel I think that makes sense to do on a PR with FR translations :+1: :fr:

**Comment by fritx** [comment]
hey i just tried to set up the Chinese one #2649
may i call some friends into this job together?

**Pull request merged**
