### PR TITLE
Detachable webview

### PR DESCRIPTION
**Pull request by arsher**
I've been looking into how to create detachable webviews, or better said something that can transfer the content into another webview instance. It might be a bit hacky currently, I'm pretty sure it's not prod quality yet, but I wanted something working to start the conversation.

I've seen #1682 which led me to the conclusion that I'm not alone with the desire to have something like this, hence this PR.

### CODE REVIEW

**Comment by deepak1556** [comment]
Nice! Just a few thoughts, could add `WebViewManager::TransferGuest(sourceGuestInstanceId, targetElementInstanceId, targetGuestInstanceId)` and let `guest-view-manger` use it to change mapping of guestinstanceid to embedder. Also `ipc` operations in `web-view` can be moved to `guest-view-internal`and ones' in `web-view-ref` can be handled by `guest-view-manager`. Not sure about the need for `WebViewRef` class.

**Comment by paulcbetts** [comment]
@arsher This is awesome, good start!

**Comment by zcbenz** [comment]
Can you add some documents for it?

**Comment by arsher** [comment]
Sure thing, I'm sorry I had about zero amount of free time, I'll try to do some docs and responses for the comments during the weekend.

**Comment by alexandernst** [comment]
Is this the same thing as https://github.com/atom/atom/issues/9334 ?

**Comment by zcbenz** [comment]
I'm closing this since there were no updates and the PR is outdated, but I'll be glad to reopen once there are new updates.

**Pull request closed without merging**
