### PR TITLE
Add support for basic auth

### LINKED ISSUE #625: Proxy support Basic Authentication?
I try to use base auth on proxy, But it does't work. atom-shell support it?
```
app.commandLine.appendSwitch('proxy-server', 'http://user:pass@ip:port');
```

### LINKED ISSUE #1362: HTTP Basic Authentication support
It seems atom shell does not support basic authentication, neither in BrowserWindow nor in webview.

It could be provided with an event in BrowserWindow and webview which defaults to a native dialog prompt.

### PR DESCRIPTION
**Pull request by zcbenz**
Close #1362
Close #625

### Event: 'login'

Returns:

* `event` Event
* `webContents` [WebContents](web-contents.md)
* `request` Object
  * `method` String
  * `url` URL
  * `referrer` URL
* `authInfo` Object
  * `isProxy` Boolean
  * `scheme` String
  * `host` String
  * `port` Integer
  * `realm` String
* `callback` Function

Emitted when `webContents` wants to do basic auth.

The default behavior is to cancel all authentications, to override this you
should prevent the default behavior with  `event.preventDefault()` and call
`callback(username, password)` with the credentials.

```javascript
app.on('login', function(event, webContents, request, authInfo, callback) {
  event.preventDefault();
  callback('username', 'secret');
})
```

### CODE REVIEW

**Comment by paulcbetts** [comment]
Nice, will this fix proxy authentication too?

**Comment by johnhaley81** [comment]
This is awesome! :heart:

**Comment by zcbenz** [comment]
> Nice, will this fix proxy authentication too?

Yeah.

**Comment by paulcbetts** [comment]
@zcbenz This is great work, thank you so much!

**Comment by tommoor** [comment]
:heart_eyes:

**Comment by Clarkey** [comment]
If anyone could build this on Windows it would be much appreciated! In a corporate environment and it's just a pain to get all the dependencies installed!

**Comment by Torquin** [comment]
Thanks for this update ! Being new on Electron I'm wondering a few things if anyone could help ? 

- does electron need updating locally to include this new "login" event ? 
- how should i implement it ? Getting "407 Proxy Authentication Required" error after using app.commandLine.appendSwitch('proxy-server','http://...')
- the "login" event doesn't seem to be triggering using the following : 

     mainWindow.webContents.on('login', fcuntion(event, webContents, request, authInfo, callback) {
       event.preventDefault();
       mainWindow.webContents.executeJavaScript("alert('Proxy OK!')");
       callback('username', 'password');
    });

Thanks for any help guys ;)

**Comment by ocombe** [comment]
Would this open a connection modal asking for credentials (like we have in browsers) or is it something that you need to implement somehow ?

**Comment by paulcbetts** [comment]
@Clarkey I fixed this in 0.34.1, but you need to call an extra method to enable it: https://github.com/atom/electron/blob/master/docs/api/app.md#appallowntlmcredentialsforalldomainsallow

**Comment by Clarkey** [comment]
@paulcbetts Thanks buddy. Got this working on the 0.34.2 release without using `app.allowNTLMCredentialsForAllDomains` - laavely!

**Comment by rodrigok** [comment]
@zcbenz Is there any way to add this event in webviews?

**Comment by sheepray** [comment]
Hi all, I am new to electron. I am wondering when the event 'login' is triggered. And what does the 'login' even mean in here? Couple lines of example codes are appreciated. Thanks.

**Comment by patrykKPOL** [comment]
this doesn't fix proxy issue. Event is getting fired, but after authorisation nothing happens.

**Comment by cphoover** [comment]
How do we trigger a modal to prompt for input?

**Comment by wiliame** [comment]
Will be nice to clear auth credentials. For example, I'm using a proxy that accepts options via username:

```
proxy.com:8080
user: wiliam_country_US
```

So, if I want to change the peer node, I change my name:

```
proxy.com:8080
user: wiliam_country_GB
```

But, I'm not changing the proxy, so electron has valid credentials and is not going to trigger `login` event.

I'm searching the way to clean auth settings so electron asks them again.

**Comment by georgiosd** [comment]
Hello,

This doesn't seem to work on the `webContents.on('login')` event - even though it gets called, I get a 407. Any way to fix?

Thanks

**Comment by vadim-ch** [comment]
Hello,
How to make it work with autoUpdate???

**Comment by wiliame** [comment]
Clear auth data is fixed in electron 1.4.12: 
https://github.com/electron/electron/issues/8089

**Comment by shrynx** [comment]
webContent returned in the function has ```nodeIntegration : false```, How do i set it to true or can we do it by default ?

**Comment by ericuldall** [comment]
Is there any suggested workflow for incorrect credentials getting sent to the callback? Currently I have a workflow where if a user trys to click a link to one of my Basic Auth pages it pops a modal over the new window with a login prompt. Assuming I enter correct credentials it works as expected however there doesn't seem to be any way of knowing if the user passed invalid credentials at which point I end up with a blank window.

Has anyone else run into this problem and/or is there something obvious i'm missing?

**Comment by vsanse** [comment]
Getting Error while implementing basic authentication:
**Code:**
```
app.on('login', (event, webContents, request, authInfo, callback) => {
  event.preventDefault()
  console.log(callback)
  secWindow = new BrowserWindow({
    width:200,
    height:200,
    parent:mainWindow,
    modal:true,
    webPreferences: {
      nodeIntegration: true
      }
  });
  secWindow.loadFile('./renderer/secondarywindows/login.html');
  ipcMain.on("loginchannel",(e,args)=>{
    loginCred = args;
    if(loginCred.canceled){
      callback()
    }
    else{
      callback(loginCred.username, loginCred.password);
    }
    secWindow = null;
  })
})
```

```
Uncaught Exception:
Error: callback can only be called for once
    at EventEmitter.<anonymous>
```

Error occurs when I try to cancel first time and submit next time, so in short login event is fired twice.Please help what am I doing wrong.

**Comment by MatthieuLeMee** [comment]
> callback()

You should do nothing when user cancels login. Like said by Electron, you cannot call `callback()` twice.
Calling it without args is useless anyway.

**Pull request merged**
