### PR TITLE
Fix `create_chrome_version_h` so it will generate chrome_version.h only if needed

### PR DESCRIPTION
**Pull request by etiktin**
chrome_version.h is generated dynamically by `bootstrap.py`, so it shouldn't be in version control (git).

### CODE REVIEW

**Comment by hokein** [comment]
@etiktin We do need this head file, it's used in Electron: https://github.com/atom/electron/search?utf8=%E2%9C%93&q=CHROME_VERSION_STRING

**Comment by etiktin** [comment]
@hokein, it's generated automatically, by [bootstrap.py](https://github.com/atom/electron/blob/master/script/bootstrap.py#L155-L172) so why do we need it in version control?
After removing it from version control it will still be genrated because the [template](https://github.com/atom/electron/blob/master/script/chrome_version.h.in) is still there.

**Comment by zcbenz** [comment]
@etiktin From technical perspective it doesn't make much sense adding `chrome_version.h` to source control, but from developer's perspective it can be quite useful.

When reading source code of a new project, one common thing is to search for a certain string to find out where and how it is defined, so if we don't have `chrome_version.h` in source code people searching for `CHROME_VERSION` will be confused, of course they can dig into the scripts and finally find out it is generated, but it is not good for them to get a better knowledge of the project easily.

Another thing is code indexer, most code searching services only generate index for code in repo, so it will cause confusions that some file is used but not exists.

So since adding `chrome_version.h` in source control hurts nothing and gains a lot for developers, I'm more willing to keep as it is.

**Comment by etiktin** [comment]
@zcbenz, okay that makes sense.
My main issue with chrome_version.h, is that every time I use bootstrap.py on Windows, git lists it as a modified file. The reason is that line endings in the file in the repo are cloned as CRLF, but the generated file uses LF (this is using GitHub Desktop on Windows with default settings).

I can solve it by modifying the `create_chrome_version_h` function in bootstrap.py so it will create the file only if it's content is actually different (ignoring line endings differences). I'll revert the previous commits and commit this instead.

**Comment by etiktin** [comment]
@zcbenz, please review the new commit.

It turns out that there was already a check in the `create_chrome_version_h` function to prevent re-writing the file when not needed ([here](https://github.com/atom/electron/blob/master/script/bootstrap.py#L171)), but it had a bug. The existing file was opened with the `w` modifier which truncates the content of the file, so the check which tried to to read it and compare it to the new content, would always return that the content is different and therefor the file was re-written.
There was another issue, that on Windows it would open the file for write in binary mode ([here](https://github.com/atom/electron/blob/master/script/bootstrap.py#L166)), which meant that when it writes the content it writes the python string with `\n` instead of the platform line ending, so that's why it kept popping up as modified (if it used the platform line ending, the first issue would still exist, but I wouldn't have noticed it since git wouldn't have marked it as modified).

The updated code compares the file content ignoring line endings and writes the file only if its different or if it didn't exist. I tested it on Windows by running bootstrap.py and build.py and everything works as expected.

**Comment by zcbenz** [comment]
Awesome, thanks!

**Pull request merged**
