### PR TITLE
Use harfbuzz 1.06

### LINKED ISSUE #4513: Rendering crashes (white screen) when FontAwesome is used (Archlinux)
With version 0.36.7 on Archlinux, if the html contains any glyph from FontAwesome, the rendering crashes and gives a white screen.

This only happens if the glyph is actually rendered, i.e. not hidden by CSS.

This can be reproduced using this example :
&lt;!DOCTYPE html&gt;

&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
	&lt;meta charset=&quot;utf-8&quot; /&gt;
	&lt;title&gt;Font Awesome Crash&lt;/title&gt;
	&lt;link href=&quot;css/font-awesome.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
&lt;/head&gt;
&lt;body&gt;
	&lt;i class=&quot;fa fa-trash-o&quot;&gt;&lt;/i&gt;
	&lt;!-- Remove the line above and the rendering works fine --&gt;
	Hello World !
&lt;/body&gt;
&lt;/html&gt;

### PR DESCRIPTION
**Pull request by zcbenz**
Close #4513.

### CODE REVIEW

**Comment by cjb** [comment]
Thanks for the fix! This was a nasty bug (Electron crashing immediately on any Linux with the newest freetype2 package installed), please could I encourage an Electron point release soon?

**Comment by zcbenz** [comment]
I usually publish releases on Friday (Beijing time), namely today.

**Comment by cjb** [comment]
Awesome, thanks very much!

**Comment by johnhaley81** [comment]
:+1: to this. It was a big bug on GitKraken.

**Pull request merged**
