### PR TITLE
Remove the "-" in BrowserWindow's option names

### LINKED ISSUE #2397: Remove hyphens (-) and keep them in camel cases - makes easy to understand and standard
This is more of a suggestion. For example,

[`min-width` or `max-width` can be `minWidth` or `maxWidth`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)

I'm from [Appcelerator background](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.Window). Whenever they have a method and property or creation option, they keep it easy like 

property - width
methods - setWidth(x) or getWidth(x)

Adding hyphens (-) brings confusions.

### PR DESCRIPTION
**Pull request by zcbenz**
e.g. `min-width` => `minWidth`. Old styles are still accepted for compatibility.

Fix #2397.
Refs #2544.

### CODE REVIEW

**Comment by etiktin** [comment]
No more quotes around option names LGTM :smile: 
Shouldn't the docs be updated as well?

**Comment by zcbenz** [comment]
> Shouldn't the docs be updated as well?

I forgot that, it has been updated now.

**Comment by etiktin** [comment]
Thanks!

**Comment by matthiasg** [comment]
just tried to get a preload script running based on the wiki documentation and electron version 0.34.3. i could not get this to work properly.

first `webPreferences` had still to be called `web-preferences` and it took me a while to find this thread which showed this was recently added and i assume the electron-quick-start is still referencing an older version.

secondly while i could get `node-integration`: false to work now (meaning require is not longer in the global page scope, as it should be) i could not get the preload script to work to expose selected modules (such as ipc) to the web application. Should this work ? preload is not well documented.

```
 mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    'web-preferences': {
      'node-integration': false,
      preload: 'file://' + path.join(__dirname, 'expose-window-apis.js')
    }
  });
```

expose-window-apis.js
```
window.ipc = require('ipc');
console.log('window.ipc', window.ipc);
```

**Comment by matthiasg** [comment]
the documentation was a little fuzzy here i got it working see https://github.com/atom/electron/issues/1753#issuecomment-157409572

**Comment by etiktin** [comment]
This PR was merged after v0.34.3 and it's first available in v0.35.0. For v0.34.3 you should use the older dashed options.
Also the preload script should be an absoulte file path, not file url. Change it to `preload: path.join(__dirname, 'expose-window-apis.js')`.

**Pull request merged**
