### PR TITLE
[WIP] protocol: adding requestHttpJob method

### LINKED ISSUE #1793: Request http{,s} job for Protocol
I want to implement an application level url rewriting, for example, when somebody accesses `example1.com/url` on http, I wanna give them `myofficeserver.com/example1.com/url` and give the same in https if the request was https.
I couldn't find a way to do that using the existing APIs.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1793

### CODE REVIEW

**Comment by steelbrain** [comment]
:heart:

**Comment by steelbrain** [comment]
@deepak1556 does it work for https too?

**Comment by deepak1556** [comment]
Its incomplete PR, just added http scheme for now, can be allowed for other schemes too but need to confirm on how the api will be used. What would be parameters passed apart from `URL` , request headers maybe ?

**Comment by steelbrain** [comment]
URL would be enough for my use case, but Yeah. requestHeaders would be cool. Also, if I rewrite the url by interception and doing requestHttpJob, will the http request contain all the cookies and stuff?

**Comment by deepak1556** [comment]
> will the http request contain all the cookies and stuff?

Nope its a completely new request context, if those data are needed then have to provision them in `request` object passed to interceptor handler, which is not done currently..

**Comment by steelbrain** [comment]
Ouch. How difficult would it be to pass that data in the request object? Can it be done in this PR or a separate PR?

**Comment by deepak1556** [comment]
@zcbenz instead of relying on creating a job from Http factory, took a more generic approach. Thoughts ?

**Comment by kjlaw89** [comment]
Hey @deepak1556, is it possible to modify the new request to send client certificates? That would go a long way in helping with my issue (https://github.com/atom/electron/issues/1221). I'm not sure if I'm following what this change would allow you to do, so I could be wrong!

**Comment by deepak1556** [comment]
@kjlaw89 yeah it is possible as there are hooks on the request object to provide certificates. But that would be just a workaround to the proper solution.

**Comment by kjlaw89** [comment]
@deepak1556 I wouldn't mind a workaround if it got me client certificates! Haha. What would be the proper solution?

Just to note, my need for client certificates is a little different. I don't want the standard browser popup for them. We're going to supply the certificate with our application and I want to be able to use the local certificate directly instead of from the system store to make things simpler for our clients.

**Comment by steelbrain** [comment]
@kjlaw89 does the nodejs request module support client certificates? 'cause If it does, the new async job in the other PR will do that for ya.

**Comment by kjlaw89** [comment]
https.request does, I believe, I don't know if http.request does or not.

**Comment by steelbrain** [comment]
The request module is built on top of the native http module, so if the native one supports that, I am pretty sure it does too.

**Comment by kjlaw89** [comment]
Are we talking about https://github.com/request/request? If so, yes it does support it, so that would work. I guess I'll just have to wait for the PR to go through and see if it works for me! Thanks!

**Comment by zcbenz** [comment]
You can use [URLFetcher](https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_fetcher.h&sq=package:chromium&type=cs) for simpler and safer implementation, current implementation leaks `net::URLRequest` object.

**Comment by deepak1556** [comment]
@zcbenz what type of writer should be used for URLFetcher ? I am thinking of using a file writer to a temporary location and start a file job with it. Or get the response as string and start a buffer job ?

**Comment by steelbrain** [comment]
@deepak1556 :-1: for writing the file to a temp location and starting a file job with it, and :+1: for the buffer job. As we can get events like did-get-response-details and stuff on time with it. We won't have to wait for the whole file to load.

**Comment by zcbenz** [comment]
You can implement a custom `URLFetcherResponseWriter` and read data into some buffer like `DrainableIOBuffer`, and then implement `ReadRawData` to stream the data. It is important to stream data instead of reading all data at once, otherwise it won't be able to handle requests to large files.

Another option is to implement with `URLRequestHttpJob::Factory`, but you have to also override at least follow methods in `AdapterRequestJob` to make it work:
https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_request_http_job.h&sq=package:chromium&type=cs&l=52
https://code.google.com/p/chromium/codesearch#chromium/src/net/url_request/url_request_http_job.h&sq=package:chromium&type=cs&l=103

**Comment by paulcbetts** [comment]
> Its incomplete PR, just added http scheme for now, can be allowed for other schemes too but need to confirm on how the api will be used. What would be parameters passed apart from URL , request headers maybe ?

For me, I would just use this as a URL redirect type of thing, nothing fancy

**Comment by steelbrain** [comment]
@paulcbetts that is my basic use case as well.

Guys, it would be great to have this implemented sooner than later as it's a blocker for a project of mine.

**Comment by zcbenz** [comment]
Closed in favor of #1995.

**Pull request closed without merging**
