### PR TITLE
Add 'pageSize' option in printToPDF API.

### PR DESCRIPTION
**Pull request by hokein**
Related to https://github.com/atom/electron/pull/1835#issuecomment-124852907.

### CODE REVIEW

**Comment by Godisemo** [comment]
To respond to your comment in the other thread. I don't agree with the unusefulness of allowing arbitrary page size. Although "export to pdf" rather than "print to pdf" would better describe what I want to do, I think it would be great to be able to reuse the code you have written. Just a few examples when arbitrary sized pdf would be necessary:

- If you use something like [reveal.js](https://github.com/hakimel/reveal.js) for creating presentations you might want to export pdf files sized to fit the screen.
- To create vector images that can be included in pdf files created by typesetting programs like latex.

I played a little with this last night by trying to adjust sizes in `atom/browser/api/lib/web-contents.coffee` but I had trouble converting pixel dimensions to metric dimensions. Also, I don't have any knowledge about the chromium printing api. Is there any reference or documentation available for it?

**Comment by hokein** [comment]
@Godisemo 
> Just a few examples when arbitrary sized pdf would be necessary:

> If you use something like reveal.js for creating presentations you might want to export pdf files sized to fit the screen.
>To create vector images that can be included in pdf files created by typesetting programs like latex.

Thanks for the explaination. 

> I played a little with this last night by trying to adjust sizes in atom/browser/api/lib/web-contents.coffee but I had trouble converting pixel dimensions to metric dimensions. 

Actually, you can specify the generated pdf page size by customizing the `mediaSize` in `web-contens.coffee`. But as was mentioned before, the `print` API is not designed for such usage, and Chromium doesn't expose such interfaces neither.

> but I had trouble converting pixel dimensions to metric dimensions.

You can do the convert as follows, assuming that the screen height dpi is the same with width's, represents by `DPI`:
* The height of pdf in microns: `window.height()*25.4/DPI` * 1000
* The width of pdf in microns: `window.width()*25.4/DPI` * 1000

> Is there any reference or documentation available for it?

Unfortunatelly, Chromium org doesn't provide any document on the print API implementation.  If you have to do it, reading the code is the only way.

**Comment by zcbenz** [comment]
Awesome!

**Comment by danburzo** [comment]
Hi guys, just wanted to let you know we've successfully exposed custom page sizes via `web_contents.js` without any side-effects as far as we can tell. How do you feel about going rogue and exposing it before there's explicit support in Chromium? (+ maybe include a disclaimer in the docs)

**Comment by Godisemo** [comment]
@danburzo I would say go for it. Who knows when the official support will be available? Noting it in the documentation would be a good idea though.

**Comment by francoislaberge** [comment]
Did this end up happening?

**Pull request merged**
