### PR TITLE
webcontents: minor patches

### LINKED ISSUE #2388: BrowserWindowProxy.closed should be initialized with false
Some libs use the instance returned by **window.open**, in this case a **BrowserWindowProxy** to check if window still is opened, mainly for oAuth.

In case of Meteor, the test expect that this instance returns closed as **false** value instead **undefined**.

I created this work around to solve my problem:

```js
windowOpen = window.open;
window.open = function() {
	result = windowOpen.apply(this, arguments);
	result.closed = false;
	return result;
} 
```

But I see no problems in return closed as false by default instead undefined and set as value only when window is closed.

### LINKED ISSUE #2413: Add the ability to know in 'will-navigate', who initiated the navigation
I think it would be helpful if the 'will-navigate' event, will contain information regarding who initiated the navigation. Some possible initiators that come to mind are: location change, form submit and drag and drop. Another option is to simply state if it was initiated internally (e.g. form submit) or externally (drag and drop).

One possible usage for this, is when you want to completely block drag and drop, but you don't want to block internal navigation (the HTML drag and drop API can also be used to do this, but if you don't control some of the resources, it's a problem).

Possible example usage:
```javascript
mainWindow.webContents.on('will-navigate', function (event, url) {
	if (event.isExternal) { // or: if (event.initiator = 'drag-and-drop')
		console.log('Preventing navigation to:', url);
		event.preventDefault();
	}
});
```

### LINKED ISSUE #2420: Request: loadcommit event on webview
It seems that Electron's <webview> tag has slightly different APIs compared to the original Chrome's <webview> tag. I was wondering if "loadcommit" event could be exposed. 

I'm building a custom browser where custom JS will be injected upon every top-level navigation before the page loads. Below is an example in nw.js. Using 'dom-ready' event would be an option, but I've noticed that loadcommit would allow the custom script to run before any other scripts (<http://stackoverflow.com/questions/26832848/chrome-apps-webview-tag-how-to-inject-css-or-js-in-time>). 

Below is an example code of injecting JS on loadcommit using nw.js. 
```javascript
webview.addEventListener("loadcommit", function(e) {
  webview.executeScript({
    file: "js/tracker.js", 
    runAt: "document_start"
  });
});
```

Thanks.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #2388 
Fixes #2420

### CODE REVIEW

**Comment by steelbrain** [comment]
What does the `load-commit` event do?

**Comment by zcbenz** [comment]
I don't #2413 is actually solved, the main purpose of that issue is to know whether the navigation is started by drag-drop, which this PR doesn't solve.

**Comment by deepak1556** [comment]
@zcbenz have removed the commit related to #2413. Does the renderer contain information on what kind of user_gesture caused the navigation ?

**Comment by zcbenz** [comment]
Looks good to me, thanks!

> Does the renderer contain information on what kind of user_gesture caused the navigation ?

I don't think we can get it from renderer.

**Pull request merged**
