### PR TITLE
Add API for checking if DWM composition (Aero Glass) is enabled

### LINKED ISSUE #1020: Windows specific api to check if DWM is enabled or not
Frameless window and transparency do not work well so it should be possible to know when `dwm` is enabled or not.

### PR DESCRIPTION
**Pull request by etiktin**
Resolves #1020.

For future reference, it is possible to disable DWM on Windows 8+ (some sources mistakenly claim it's only possible in Vista and 7). Instructions are available [here](http://www.overclock.net/t/1441921/windows-8-1-no-dwm-aka-aero-aka-desktop-composition#post_22483531).

### CODE REVIEW

**Comment by zcbenz** [comment]
:+1:

**Comment by paulcbetts** [comment]
Can we rename this method to `supportsTransparentWindows` so that we can make this a check that makes sense on all platforms (and aren't pigeonholed into a single reason of many that transparent windows will fail?)

**Comment by zcbenz** [comment]
@paulcbetts They are not exactly the same thing, transparent window may also fail when GPU acceleration is not available, and I don't think there is a way to detect whether transparent window may work on other platforms.

**Comment by paulcbetts** [comment]
@zcbenz Sure, but at least at the moment we can cover one scenario where they won't work then maybe in the future find a way to cover others. I just don't want to hard-code in such a specific one-off cause when the real goal is something else

**Comment by etiktin** [comment]
The current method just answers the question "is DWM enabled?" (the name `isAeroGlassEnabled` was used, because that's how Chromium calls it). If we call it `supportsTransparentWindows`, the user will have an expectation that if it returns true, transparent windows will surly work, which is not the case.
So for now, I would leave it as is. In the future, if we find a way to truly answer that question, we can mark this method as deprecated and recommend that everyone move to the new one.

**Comment by LukePulverenti** [comment]
I agree about supportsTransparentWindows. I think that would be more useful in that would help developers avoid platform-specific conditionals.

**Pull request merged**
