### PR TITLE
webContents: providing dom-ready event

### LINKED ISSUE #1504: WebContents `dom-ready` event
I would like to use `WebContents.insertCSS()` as soon as the DOM is ready.

I tried using `WebContents.on('did-finish-load')`, but you can see the page being loaded before the CSS is applied.

My workaround is to have the following in a `preload` JS file:

```js
document.addEventListener('DOMContentLoaded', function () {
	ipc.send('dom-ready');
});
```

and listen to the IPC event in the main renderer.

But it would be a lot nicer to have an event for this.

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #1504

### CODE REVIEW

**Comment by deepak1556** [comment]
Should the readyState of the document be interactive or complete during this event ? Coz its interactive during domcontentloaded but it will be complete here. Plus this event is equal to loading content scripts at document_end. If you need the event to be fired as soon as `window.document` is available then the method has to changed.

/cc @sindresorhus @zcbenz

**Comment by sindresorhus** [comment]
I would like it to be `interactive` to match `DOMContentLoaded`.

Could maybe have another event for `complete`, to match Chrome extension's `document_start` and `document_end`.

**Comment by deepak1556** [comment]
@sindresorhus have added test and works as expected, i forgot to test with sub resources yesterday.
@zcbenz i wrote the test based on an external resource which is bad, any other option to test ? Or do i remove it.

**Comment by deepak1556** [comment]
Fixed test with local server.

**Comment by zcbenz** [comment]
Thanks!

**Comment by sindresorhus** [comment]
@deepak1556 Nice work! Thanks for implementing :)

**Pull request merged**
