### PR TITLE
Translate docs into korean #2 + added link of power-save-blocker API to README

### PR DESCRIPTION
**Pull request by preco21**
Second PR of korean translation!

Currently, documents of developers and tutorials were completely translated. However, API docs are still 11 files not yet translated. So the translation is not yet fully completed(still), but also I will translate the remained files soon.

And added the missing link of `power-save-blocker` API docs to README. (related #2025)

### CODE REVIEW

**Comment by zcbenz** [comment]
Thanks!

**Comment by dalinaum** [comment]
There are many untralslated files:

* docs/api/app-ko.md
* docs/api/auto-updater-ko.md
* docs/api/browser-window-ko.md
* docs/api/chrome-command-line-switches-ko.md
* docs/api/content-tracing-ko.md
* docs/api/crash-reporter-ko.md
* docs/api/dialog-ko.md
* docs/api/frameless-window-ko.md
* docs/api/menu-ko.md
* docs/api/remote-ko.md
* docs/api/screen-ko.md

I think you should not have added these files into PR. Please seperate fully translated files from your next work and push your next PR clearly.

**Comment by preco21** [comment]
Thank you for check that point!

However, translation is almost finished. Probably next PR is seems to be last translation PR.
Currently, there are **5** files that are not translated.

* docs/api/auto-updater-ko.md
* docs/api/remote-ko.md
* docs/api/content-tracing-ko.md
* docs/api/web-view-tag-ko.md
* docs/api/browser-window-ko.md

**Comment by dalinaum** [comment]
:+1:

**Pull request merged**
