### PR TITLE
Run callback of setDestructor immediately when GC happens

### LINKED ISSUE #4733: Exception in objects-registry when doing remote work
* Electron version: 0.36.9
* Operating system: Mac

We're still trying to nail down repro steps in Slack, but it seems to happen on 0.36.9 when calling `remote` methods. Specifically, we build context menus using `remote` (very similar to the [`Menu`](https://github.com/atom/electron/blob/master/docs/api/menu.md) sample) and occasionally they stop working with this exception:
```
Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
  at ObjectsRegistry.get (C:\Users\paulb\AppData\Local\slack\app-2.0.2\resources\atom.asar\browser\lib\objects-registry.js:44:28)
  at metaToValue (C:\Users\paulb\AppData\Local\slack\app-2.0.2\resources\atom.asar\browser\lib\rpc-server.js:155:32)
  at Array.map (native)
  at unwrapArgs (C:\Users\paulb\AppData\Local\slack\app-2.0.2\resources\atom.asar\browser\lib\rpc-server.js:214:15)
  at EventEmitter.<anonymous> (C:\Users\paulb\AppData\Local\slack\app-2.0.2\resources\atom.asar\browser\lib\rpc-server.js:317:12)
  at emitMany (events.js:108:13)
  at EventEmitter.emit (events.js:182:7)
  at EventEmitter.<anonymous> (C:\Users\paulb\AppData\Local\slack\app-2.0.2\resources\atom.asar\browser\api\lib\web-contents.js:133:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
```

### PR DESCRIPTION
**Pull request by zcbenz**
@mitchhentges Can you try if this fixes #4733 for you? I can't reproduce the original issue so I'm not able to try it myself.

### CODE REVIEW

**Comment by mitchhentges** [comment]
Sure, just need to set up the reproduce scenario again

**Comment by mitchhentges** [comment]
Looks good, I tested two things:
1. `electron-connect` which is failing on `v0.37.2`
2. Having two inputs: one of them uses a script's root-level-scope version of `window`, and `console.log`s it. The other one is a closure as follows:
```
(function() {
const window = remote.getCurrentWindow();
console.log(window)
}());
```
Ideally, if there was something wrong with the destructor, the closure would cause a GC every time that it finished executing.

Both cases succeeded. :+1:

**Comment by mitchhentges** [comment]
@zcbenz just to confirm, this is good to be merged, imho.
I'm not sure if you were still waiting on a response, or leaving this PR on purpose :)

**Comment by zcbenz** [comment]
@mitchhentges I wanted to leave it open for a while to collect possible feedbacks, since it may have other side effects. I'm merging now.

**Pull request merged**
